version: '3'

services:
  postgres:
    image: postgres:15

    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD must be set}
      POSTGRES_DB: ${DB_NAME:-automation}

    ports:
      - "5432:5432"